void OutPut_Initialize();
void OutPut_SingleGrid_while_Input(int x, int y, int value);
void OutPut_Exclude_NumInGrid(int line, int column);
void OutPut_Exclude_NumInLine(int nums_in_line[10], int count_nums_in_line);
int CollectLine(int index_direction, int index_line, int x, int y);
void MyGetchar(int x, int y);
void MyGetchar_Try(int x, int y);
void TryInPutNum();
void InputNum();
void Convert_Sodoku_to_CNF();
void Convert_CNF_to_Sodoku();